######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 20 11:35:02 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += t1.cpp
