######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 28 19:03:33 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += AllClasses.h mouse.h System.h
SOURCES += main.cpp mouse.cpp System.cpp Vector.cpp
