######################################################################
<<<<<<< HEAD
# Automatically generated by qmake (2.01a) Sun Oct 28 19:03:33 2012
=======
# Automatically generated by qmake (2.01a) Sun Oct 28 15:39:04 2012
>>>>>>> 2103f4d72d69867903b3452dad9d9da628b41011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += AllClasses.h mouse.h System.h
SOURCES += main.cpp mouse.cpp System.cpp Vector.cpp
