######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 27 01:18:11 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mouse.h
SOURCES += main.cpp mouse.cpp
